### ISSUE TITLE
Crashing with maximum baits 

### ISSUE THREAD

**Issue by DantasB** [tiemonl/Bit-Heroes-Fishing-Bot#40] opened 2019-09-26 01:57 UTC
When you try to use a lot of baits (more than 800) the app crashes.

**Comment by tiemonl** [comment] 2019-09-26 01:59
Did the app get to 800 or when you input 800? Logs? Screenshots? Version? OS?Information is a bit vague...

**Comment by DantasB** [comment] 2019-09-26 02:08
Sorry for the bad information :/
The input was 1000 but the app crashed. I didn't get the logs and screenshots.
The version is 1.4.0
OS is Windows

**Comment by tiemonl** [comment] 2019-09-26 02:13
No problem. It’s just hard for me to try and fix anything if I have no information.

Are you using the GUI program or the command line? Try using the other one?

It may have been a one off issue... if you restart the bot it works again, correct? Something may have happened in the background to cause some lag and made my program miss a step and couldn’t recover?

**Comment by DantasB** [comment] 2019-09-26 02:25
I'm using the GUI program.
I'm running the bot again. I will try to input 1000 baits again and let it run. If it bug again or something else i will send a print :)

**Comment by DantasB** [comment] 2019-09-26 02:32
![image](https://user-images.githubusercontent.com/15825133/65653740-b399fc80-dfec-11e9-965a-850b664d966e.png)
Crashed with 19 baits. I don't know if it's the computer or something else.

**Comment by tiemonl** [comment] 2019-09-26 02:36
It looks like it got out of sync for some reason. I could increase the timings. Does the java version run into the same issue?

**Comment by DantasB** [comment] 2019-09-26 08:11
I found where. It always crashing when the bait changes.

**Comment by tiemonl** [comment] 2019-09-26 22:15
I fished with 300 bait including 2 bait changes and I wasn't able to reproduce 😕

**Comment by tiemonl** [comment] 2019-09-30 23:46
I'm going to close this as I cannot reproduce, Feel free to reopen the issue if it keeps happening.

**Closed as completed by tiemonl** 2019-09-30 23:46 UTC
